baseURL       = "http://aubeaujeu.com/WIP/"
languageCode  = "fr-FR"
title         = "Au Beau Jeu | Boutique & bar à jeux, Lille"
theme         = "roxo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Accueil"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "La boutique"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Le bar à jeux"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "Quoi de neuf ?"
    url     = "blog"
    weight  = 4
  [[menu.nav]]
    name    = "Contactez-nous"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "16 SEP 2020"
  # Meta data
  description = "Au Beau Jeu | Boutique & bar à jeux, Lille"
  author = "Au Beau Jeu"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/myykjpje"

  custom_css = ["css/main.css"]

  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"


  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "Au Beau Jeu n'attends que vous pour vos soirées jeux"
    tagline               = "VOTRE NOUVEL ENDROIT FAVORI SUR LILLE"
    primary_button        = "La boutique"
    primary_button_url    = "portfolio"
    secondary_button      = "Le bar à jeux"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = true
    title     = "Vous souhaitez venir ?"
    subtitle  = ""

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "On a hâte de vous faire jouer !"
    primary_button      = "J'arrive !"
    primary_button_url  = "contact"
    secondary_button    = "Je fonce !"
    secondary_button_url = "contact"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Nos coordonnées"
      address = "127 Rue du Molinel, <br>59800 Lille"
      phone   = "06 27 09 88 73"
      email   = "aubeaujeu@gmail.com"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "La boutique"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Le bar à jeux"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Quoi de neuf ?"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contactez-nous"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Nos réseaux sociaux"
        [[params.footer.social.link]]
          name = '<span class="fa-stack fa-lg"><i class="fa fa-circle-thin fa-stack-2x"></i><i class="fa fa-facebook fa-stack-1x"></i></span>'
          url  = "https://www.facebook.com/AuBeauJeu/"
        [[params.footer.social.link]]
          name = '<span class="fa-stack fa-lg"><i class="fa fa-circle-thin fa-stack-2x"></i><i class="fa fa-instagram fa-stack-1x"></i></span>'
          url  = "https://www.instagram.com/aubeaujeu/?hl=fr+au+beau+jeu"
      # Footer Service
      [params.footer.service]
        title       = "Blabla bla:"
        description = "blabla blabla blabla<br>blabla blabla blabla blabla<br>blabla blabla blabla blabla"
